from app.enums import StrEnum


class OSVarsEnum(StrEnum):
    DB_NAME = "DB_NAME"
    DATABASE_URL = "DATABASE_URL"
    JWT_SECRET_KEY = "JWT_SECRET_KEY"
    ENV = "ENV"
    REDIS_HOST = "REDIS_HOST"
    REDIS_PORT = "REDIS_PORT"
    REDIS_USERNAME = "REDIS_USERNAME"
    REDIS_PWD = "REDIS_PWD"
    THIRD_PARTY_SECRET_KEY = "THIRD_PARTY_SECRET_KEY"